### ISSUE TITLE
Simplify CSS for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [nemosfate/prj-rev-bwfs-dasmoto#9]
It is a good idea to try and simplify the CSS code as much as you can to make the code cleaner and to remove repetitive code. There are a few shared properties that you can simplify by applying to multiple selectors at once, rather than individually. For instance, for the h2 elements,

```css
h2 {
  font-weight: bold;
  font-size: 32px;
  color: white;
}
```
